packages:
  flow-sight-backend/internal/handlers:
    interfaces:
      BankAccountServiceInterface:
      CreditCardServiceInterface:
      AuthServiceInterface:
      RecurringPaymentServiceInterface:
      IncomeServiceInterface:
