{{- if and (not .Values.backend.secrets.externalName) (or .Values.backend.secrets.GOOGLE_CLIENT_ID .Values.backend.secrets.GOOGLE_CLIENT_SECRET .Values.backend.secrets.DB_PASSWORD .Values.backend.secrets.JWT_SECRET) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flow-sight.fullname" . }}-backend-secrets
  labels:
    {{- include "flow-sight.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
data:
  {{- if .Values.backend.secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_ID: {{ .Values.backend.secrets.GOOGLE_CLIENT_ID | b64enc }}
  {{- end }}
  {{- if .Values.backend.secrets.GOOGLE_CLIENT_SECRET }}
  GOOGLE_CLIENT_SECRET: {{ .Values.backend.secrets.GOOGLE_CLIENT_SECRET | b64enc }}
  {{- end }}
  {{- if .Values.backend.secrets.DB_PASSWORD }}
  DB_PASSWORD: {{ .Values.backend.secrets.DB_PASSWORD | b64enc }}
  {{- end }}
  {{- if .Values.backend.secrets.JWT_SECRET }}
  JWT_SECRET: {{ .Values.backend.secrets.JWT_SECRET | b64enc }}
  {{- end }}
{{- end }}
