{{- if and (not .Values.backend.secrets.externalName) (.Values.backend.secrets.DB_PASSWORD) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flow-sight.fullname" . }}-backend-secret
  labels:
    {{- include "flow-sight.labels" . | nindent 4 }}
stringData:
  DB_PASSWORD: {{ .Values.backend.secrets.DB_PASSWORD }}
{{- end }}
